groups:
  - name: UsingTooMuchMemory
    rules:
      - alert: UsingTooMuchMemory
        expr: node_memory_MemFree_bytes < 1000000
        for: 1m
        labels:
          severity: critical
        annotations:
          title: "Instance {{$labels.instance}} is almost out of memory"
          description: "{{$labels.instance}} of job {{$labels.job}} has been down"
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          title: "Instance {{$labels.instance}} is down"
          description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 1 minutes."
